version: 1.05a{build}
branches:
  only:
  - master
max_jobs: 15
image: Visual Studio 2017
configuration:
  - Debug
  - Release
platform: Any CPU
build:
  project: zlib.net.sln
  parallel: true
  verbosity: minimal
test: off
environment:
  access_token:
    secure: oHqKZpK6huL4v9LT6ifeFb/MA3vI1NRlN66jP+qbI7DiGhV0ZF3L7xmTeJR+OEFG
  matrix:
  - somedummything: false
  - skip_rebase: true
matrix:
  exclude:
   - configuration: Debug
     skip_rebase: true
   - configuration: Release
     somedummything: false
on_success:
- ps: >-
    if ($env:skip_rebase -eq "")

    {

    git config --global credential.helper store

    Add-Content "$HOME\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"

    git config --global user.email "seandhunt_7@yahoo.com"

    git config --global user.name "AraHaan"

    git checkout -q patches

    git format-patch -q master -o ./patches/

    git checkout -q master

    # delete patches branch from remote and locally
    git push origin --delete patches

    git branch -q -D patches

    # recreate branch to simulate a rebase.
    git branch -q patches

    git checkout -q patches

    git am -q ./patches/*.patch

    # push the now simulated rebased branch to github.
    git push -q --set-upstream origin patches

    }