version: 1.03a{build}
branches:
  only:
  - master
max_jobs: 15
image:
 - Visual Studio 2017
 - Visual Studio 2017 Preview
configuration:
  - Debug
  - Release
platform:
 - x86
 - x64
build:
  project: zlib.net.sln
  parallel: true
  verbosity: minimal
test: off
