version: 1.05a{build}
branches:
  only:
  - master
max_jobs: 15
image: Visual Studio 2017
configuration:
  - Debug
  - Release
platform: Any CPU
build:
  project: zlib.net.sln
  parallel: true
  verbosity: minimal
test: off
