name: .NET Core (build pull request)

on: [pull_request]

jobs:
  build:

    runs-on: windows-latest

    steps:
    # clone the parent repository.
    - uses: actions/checkout@v2
      with:
        repository: 'Elskom/Sdk'
        ref: 'master'
        path: 'Sdk'
    # clone this one too.
    - uses: actions/checkout@v2
      with:
        path: 'Sdk/zlib.managed'
    # this sadly has to match the parent repository.
    - name: .NET core build
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.102
    - name: Build with dotnet
      run: |
        cd Sdk/GitBuildInfo
        dotnet build --configuration Release
        cd ..
        dotnet build --configuration Release
