name: .NET Core (build & publish pre-release)

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_NOLOGO: true
    steps:
    # clone the parent repository.
    - uses: actions/checkout@v2
      with:
        repository: 'Elskom/Sdk'
        ref: 'main'
        path: 'Sdk'
    # clone this one too.
    - uses: actions/checkout@v2
      with:
        path: 'Sdk/zlib.managed'
    # this sadly has to match the parent repository.
    - name: .NET core build
      uses: actions/setup-dotnet@v1.8.0
      with:
        dotnet-version: 6.0.100-preview.3.21202.5
    - name: Restore
      run: |
        cd Sdk/
        dotnet restore
      shell: bash
    - name: Build with dotnet
      run: |
        cd Sdk/
        dotnet build --configuration Release --no-restore
      shell: bash

    # - name: Publish Pre-release
    #   id: publish_nuget
    #   uses: rohith/publish-nuget@v2
    #   with:
    #     # Filepath of the project to be packaged, relative to root of repository
    #     PROJECT_FILE_PATH: zlib.managed.csproj
    #     # Flag to toggle git tagging, enabled by default
    #     TAG_COMMIT: false
    #     # API key to authenticate with NuGet server
    #     NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    #     INCLUDE_SYMBOLS: true
