name: .NET Core (build pull request)

on: [pull_request]

jobs:
  build:
    runs-on: windows-latest
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
    steps:
    - uses: actions-ecosystem/action-remove-labels@v1.1.0
      continue-on-error: true
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        labels: |
          enhancement
          automerge

    # clone the parent repository.
    - uses: actions/checkout@v2
      with:
        repository: 'Elskom/Sdk'
        ref: 'main'
        path: 'Sdk'
    # clone this one too.
    - uses: actions/checkout@v2
      with:
        path: 'Sdk/zlib.managed'
    # this sadly has to match the parent repository.
    - name: .NET core build
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.102
    - name: Restore
      run: |
        cd Sdk/
        dotnet restore
      shell: bash
    - name: Build with dotnet
      run: |
        cd Sdk/
        dotnet build --configuration Release --no-restore
      shell: bash

    # auto approve pull request if from repository admins or even dependabot.
    - uses: hmarr/auto-approve-action@v2.0.0
      if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]' || github.actor == 'AraHaan' || github.actor == 'CatGirlsAreLife' || github.actor == 'Raitou' || github.actor == 'JunichiSama' || github.actor == 'xioke' || github.actor == 'Elskom-gitsync'
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
    - uses: actions-ecosystem/action-add-labels@v1
      if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]' || github.actor == 'AraHaan' || github.actor == 'CatGirlsAreLife' || github.actor == 'Raitou' || github.actor == 'JunichiSama' || github.actor == 'xioke' || github.actor == 'Elskom-gitsync'
      with:
        github_token: ${{ secrets.GITSYNC_TOKEN }}
        labels: |
          enhancement
          automerge
